name: Run Cypress Tests in Docker

on:
  push:
    branches:
      - task17
  pull_request:
    branches:
      - task17

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: cypress/included:12.3.0  
        options: --entrypoint "/bin/bash"  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Cypress tests in Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/e2e \
            -w /e2e \
            cypress/included:12.3.0 \
            cypress run  
