name: Cypress Tests in Docker

on:
  push:
    branches:
      - main   
  pull_request:
    branches:
      - main   

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    services:
      docker:
        image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
        options: --entrypoint="" 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run Cypress tests inside Docker
        run: |
          docker run --rm -v $(pwd):/e2e -w /e2e cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1 /bin/bash -c "npm ci && npx cypress run"
